version: "3.3"
services:
  cassandra-one:
    image: library/cassandra:3.11.10
    ports:
      - "9042:9042"
    environment:
      MAX_HEAP_SIZE: "128M"
      MIN_HEAP_SIZE: "128M"
      HEAP_NEWSIZE: "24M"
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
